/*
 * Turns a word into the pen strokes the hero writes, ahead of time.
 *
 * The HandwritingText component on the landing page draws a word as if by pen.
 * A web font renders as filled shapes with no outline, so the glyphs have to be
 * converted to paths before there is anything to stroke. The original component
 * did that in the browser: a CDN script for opentype.js and a runtime font
 * fetch, on every visit, before the headline could draw.
 *
 * The word never changes, so the conversion happens here once instead, and the
 * page ships the finished geometry: no third-party script, no font request, and
 * the headline renders in the prerendered HTML rather than after hydration.
 *
 *   node scripts/handwriting.mjs "page." "Sidq"
 *
 * Writes src/components/landing/handwriting.ts, one entry per word. Caveat is
 * SIL OFL 1.1.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import opentype from "opentype.js";

const here = dirname(fileURLToPath(import.meta.url));
// Every word the site writes by hand, generated together so they share a pen.
const words = process.argv.length > 2 ? process.argv.slice(2) : ["page.", "Sidq"];
const EM = 100;

const buffer = readFileSync(join(here, "fonts", "Caveat.ttf"));
const font = opentype.parse(buffer.buffer.slice(buffer.byteOffset, buffer.byteOffset + buffer.byteLength));

function geometry(text) {
  const path = font.getPath(text, 0, EM, EM);
  const box = path.getBoundingBox();
  const pad = EM * 0.12;
  const full = path.toPathData(2);
  return {
    text,
    full,
    // One path per contour: a dash pattern restarts at every subpath, so the pen
    // can only cross the word left to right if each contour is its own element.
    contours: full.split(/(?=M)/).filter((d) => d.trim().length > 1),
    viewBox: [box.x1 - pad, box.y1 - pad, box.x2 - box.x1 + pad * 2, box.y2 - box.y1 + pad * 2].map(
      (n) => Math.round(n * 100) / 100,
    ),
  };
}

const out = Object.fromEntries(words.map((w) => [w, geometry(w)]));

const target = join(here, "..", "src", "components", "landing", "handwriting.ts");
writeFileSync(
  target,
  `// Generated by scripts/handwriting.mjs from Caveat (SIL OFL 1.1). Do not edit.\n` +
    `export const HANDWRITING = ${JSON.stringify(out, null, 2)} as const;\n\n` +
    `export type HandwrittenWord = keyof typeof HANDWRITING;\n`,
);
for (const w of words) console.log(`${w}: ${out[w].contours.length} contours`);
console.log(`-> ${target}`);
