#!/usr/bin/env bash
#
# Sidq setup. Takes a fresh clone to something that builds, and hands the
# backend to the script that actually deploys it.
#
#   ./scripts/setup.sh
#
# ── Why this is short now ───────────────────────────────────────────────────
# The previous version set up a different product. It asked for an Anthropic
# key it called the one secret the product could not run without, ran a
# quality gate on a planner, generated web-push keys, and deployed three edge
# functions — generate-day, register-push, send-ritual-push — none of which
# exist. It never deployed the five that do and never set the secrets they
# read. Production was configured by hand, correctly, and this script could not
# have reproduced it.
#
# So it no longer tries to know the backend. `deploy-functions.sh` reads the
# function list from the directory and the secrets from a gitignored file, and
# this calls it.
set -euo pipefail

cd "$(dirname "$0")/.."

BOLD=$'\033[1m'; DIM=$'\033[2m'; RED=$'\033[31m'; GREEN=$'\033[32m'
YELLOW=$'\033[33m'; OFF=$'\033[0m'

say()  { printf '%s\n' "$*"; }
step() { printf '\n%s▸ %s%s\n' "$BOLD" "$*" "$OFF"; }
ok()   { printf '  %s✓%s %s\n' "$GREEN" "$OFF" "$*"; }
warn() { printf '  %s!%s %s\n' "$YELLOW" "$OFF" "$*"; }
die()  { printf '  %s✗%s %s\n' "$RED" "$OFF" "$*"; exit 1; }
note() { printf '  %s%s%s\n' "$DIM" "$*" "$OFF"; }

ENV_FILE=".env.local"

say "${BOLD}Sidq setup${OFF}"

# ---------------------------------------------------------------------------
step "Prerequisites"
# ---------------------------------------------------------------------------
command -v node >/dev/null || die "node is not installed. Get it from nodejs.org"
NODE_MAJOR=$(node -p "process.versions.node.split('.')[0]")
[ "$NODE_MAJOR" -ge 20 ] || die "node 20+ required, found $(node -v)"
ok "node $(node -v)"

command -v cargo >/dev/null || die "Rust is not installed. Get it from rustup.rs"
ok "cargo $(cargo --version | cut -d' ' -f2)"

[ -d node_modules ] || { step "Installing dependencies"; npm install; }
ok "dependencies"

# ---------------------------------------------------------------------------
step "Client config ($ENV_FILE)"
# ---------------------------------------------------------------------------
# Only what the bundle reads. Anything prefixed VITE_ is compiled into the app
# and the site and is public, which is why nothing secret goes here.
if [ -f "$ENV_FILE" ] && grep -q '^VITE_SUPABASE_URL=.\+' "$ENV_FILE"; then
  ok "already written"
else
  say "  From the Supabase dashboard, Project Settings > API:"
  printf '  Project URL (https://xxxx.supabase.co): '
  read -r SUPABASE_URL
  printf '  anon public key: '
  read -r SUPABASE_ANON
  [ -n "$SUPABASE_URL" ] && [ -n "$SUPABASE_ANON" ] || die "both are needed"

  cat > "$ENV_FILE" <<EOF
# Generated by scripts/setup.sh
# Anything prefixed VITE_ is compiled into the bundle and is PUBLIC.

VITE_SUPABASE_URL=$SUPABASE_URL
VITE_SUPABASE_ANON_KEY=$SUPABASE_ANON

# Optional. A per-seat price for the Team card. Unset, the card reads
# "Let's talk", which is right until a real number has been decided.
# VITE_TEAM_SEAT_PRICE=
EOF
  chmod 600 "$ENV_FILE"
  ok "written"
fi

git check-ignore -q "$ENV_FILE" && ok "$ENV_FILE is gitignored" \
  || warn "$ENV_FILE is not gitignored — add it before committing"

# ---------------------------------------------------------------------------
step "Checks"
# ---------------------------------------------------------------------------
npm run --silent typecheck && ok "types" || die "typecheck failed"
npm test --silent >/dev/null && ok "web tests" || die "web tests failed"
note "Rust tests: cd src-tauri && cargo test (slow on first run)"

# ---------------------------------------------------------------------------
step "Backend"
# ---------------------------------------------------------------------------
if [ -f supabase/.env.functions ]; then
  say "  Deploy the edge functions and their secrets now? [y/N] "
  read -r GO
  if [[ "$GO" =~ ^[Yy]$ ]]; then
    ./scripts/deploy-functions.sh
  else
    note "skipped. Run ./scripts/deploy-functions.sh when ready."
  fi
else
  note "No supabase/.env.functions yet, so the backend is not touched."
  note "  cp supabase/.env.functions.example supabase/.env.functions"
  note "  fill it in, then ./scripts/deploy-functions.sh"
fi

# ---------------------------------------------------------------------------
step "Done"
# ---------------------------------------------------------------------------
say "  Site:        ${BOLD}npm run dev${OFF}"
say "  Desktop app: ${BOLD}npm run desktop${OFF}"
say ""
say "  ${DIM}Still manual, because they need decisions rather than commands:${OFF}"
say "  ${DIM}- Auth providers: Supabase > Authentication > Providers.${OFF}"
say "  ${DIM}- Stripe products and the webhook endpoint, then their IDs into${OFF}"
say "  ${DIM}  supabase/.env.functions.${OFF}"
